language: csharp
solution: CSharp.Rop.GenericResult.sln
install:
  - nuget restore CSharp.Rop.GenericResult.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release CSharp.Rop.GenericResult.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./CSharp.Rop.GenericResult.Tests/bin/Release/CSharp.Rop.GenericResult.Tests.dll